### ISSUE TITLE
Code does not build after following instructions.

### ISSUE THREAD

**Issue by anewton** [Datasilk/Kandu#1]
Code does not build after following instructions.  Sql library not included in the Query project, perhaps on purpose to break your apps?  Not really open source if it doesn't include all dependencies and build after cloning.  Will you fix this?

**Comment by anewton** [comment]
Also just did another fresh clone and found errors.  So it works on your machine but not others, it seems.

Yes, the database publish instructions worked fine.  Published a database named "Kandu" to (localdb)\projectsv13 local dev database server.  No issue there.  It's the Query project dependency on some object called Sql.  Not sure which namespace that is supposed to come from, but that is definately the issue.  

Attempted a dotnet restore at the root of the source code folder and found this error:
error NU1003: PackageTargetFallback and AssetTargetFallback cannot be used together. Remove PackageTargetFallback(deprecated) references from the project environment. [C:\repos\kandu\Kandu.sln]

Using VS2017 to run a build and found 45 errors (1 other was that Query.dll could not be build):
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	101	Active
Error	CS0006	Metadata file 'C:\repos\Kandu\Query\bin\Debug\netcoreapp2.0\Query.dll' could not be found	Kandu	C:\repos\Kandu\App\CSC	1	Active
Error	CS0019	Operator '<' cannot be applied to operands of type 'int' and 'method group'	Query	C:\repos\Kandu\Query\Query\Boards.cs	92	Active
Error	CS0019	Operator '<' cannot be applied to operands of type 'int' and 'method group'	Query	C:\repos\Kandu\Query\Query\Boards.cs	95	Active
Error	CS0019	Operator '>' cannot be applied to operands of type 'method group' and 'int'	Query	C:\repos\Kandu\Query\Query\Boards.cs	48	Active
Error	CS0019	Operator '>' cannot be applied to operands of type 'method group' and 'int'	Query	C:\repos\Kandu\Query\Query\Boards.cs	61	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	11	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	27	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	41	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	54	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	67	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	108	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	120	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Boards.cs	131	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	10	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	26	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	43	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	54	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	68	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	79	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	90	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	104	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Cards.cs	117	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Lists.cs	9	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Lists.cs	22	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Lists.cs	36	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Lists.cs	47	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Lists.cs	60	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Lists.cs	71	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Teams.cs	9	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Teams.cs	24	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Teams.cs	38	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Teams.cs	61	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	9	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	23	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	36	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	48	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	59	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	70	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	80	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	90	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	106	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	111	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	122	Active
Error	CS0103	The name 'Sql' does not exist in the current context	Query	C:\repos\Kandu\Query\Query\Users.cs	133	Active
Error	CS0246	The type or namespace name 'Connection' could not be found (are you missing a using directive or an assembly reference?)	Query	C:\repos\Kandu\Query\Query\Boards.cs	79	Active

**Comment by markentingh** [comment]
Make sure that when you cloned the repository that you did a recursive clone, since there are many sub modules included in the project. Sql.cs is part of a sunmodule locates in Query/Core folder. If that folder is empty, then you’ll need to run a command in the project root ‘git submodule update —init ‘

**Comment by anewton** [comment]
That was the issue.  I simply did a git clone of the repo without the --recurse-submodules option.  Thank you.  Force of habit not to include that for a repo clone.  The application now runs and drops me into the login page.  Which doesn't allow me past it.  But that is a different issue that I'll work through looking at the code.  Thank you!!

**Comment by anewton** [comment]
Fixed

**Comment by markentingh** [comment]
It's all good, I do the same thing all the time. Closing this issue :)
