### ISSUE TITLE
 I cloned the kandu project, but....

### ISSUE THREAD

**Issue by andersonapaixao** [Datasilk/Kandu#10]
hello, I cloned the kandu project, created the database, with all the scripts, but when running, a screen appears to register a master user, but it does nothing, a blank screen appears. I would like to know if there is a step-by-step guide. Thanks.

**Comment by markentingh** [comment]
@andersonapaixao sorry about that. I did a clean install and found the issue related to an empty boards page, so now the page will display a "Create New Board" button for your personal organization and also any organizations you are a part of where you also have permission to create new boards where the organization has zero boards.
